// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SolarSystem.DataAccess1;

#nullable disable

namespace SolarSystem.DataAccess1.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260314214250_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SolarSystem.Models1.Models.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Admins");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PasswordHash = "secret_hash",
                            Role = "MasterAdmin",
                            Username = "master_chief"
                        });
                });

            modelBuilder.Entity("SolarSystem.Models1.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("SolarSystem.Models1.Models.CustomerFeedBack", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("CustomerFeedBacks");
                });

            modelBuilder.Entity("SolarSystem.Models1.Models.CustomerFeedbackTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerFeedbackId")
                        .HasColumnType("integer");

                    b.Property<string>("FeedbackText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CustomerFeedbackId");

                    b.ToTable("CustomerFeedbackTranslations");
                });

            modelBuilder.Entity("SolarSystem.Models1.Models.CustomerTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<string>("Job")
                        .HasColumnType("text");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("CustomerTranslations");
                });

            modelBuilder.Entity("SolarSystem.Models1.Models.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Images");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ProductId = 1,
                            RelativePath = "/images/panel1.png"
                        },
                        new
                        {
                            Id = 2,
                            ProductId = 1,
                            RelativePath = "/images/panel1.png"
                        },
                        new
                        {
                            Id = 3,
                            ProductId = 2,
                            RelativePath = "/images/inverter1.jpg"
                        });
                });

            modelBuilder.Entity("SolarSystem.Models1.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<int>("SectionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SectionId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Price = 500.00m,
                            SectionId = 1
                        },
                        new
                        {
                            Id = 2,
                            Price = 1200.00m,
                            SectionId = 2
                        });
                });

            modelBuilder.Entity("SolarSystem.Models1.Models.ProductTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MainDesc")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<string>("SubDesc")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductTranslations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LanguageCode = "en",
                            MainDesc = "High efficiency panel",
                            Name = "Super Solar 3000",
                            ProductId = 1
                        },
                        new
                        {
                            Id = 2,
                            LanguageCode = "en",
                            MainDesc = "Pure sine wave inverter",
                            Name = "MaxVolt Inverter",
                            ProductId = 2
                        },
                        new
                        {
                            Id = 3,
                            LanguageCode = "ar",
                            MainDesc = "لوح عالي الكفاءة",
                            Name = "سوبر سولار 3000",
                            ProductId = 1
                        },
                        new
                        {
                            Id = 4,
                            LanguageCode = "ar",
                            MainDesc = "محول موجة جيبية نقية",
                            Name = "ماكس فولت إنفرتر",
                            ProductId = 2
                        });
                });

            modelBuilder.Entity("SolarSystem.Models1.Models.ProjectCardTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("LocationText")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("ProjectCardId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectCardId");

                    b.ToTable("ProjectCardTranslations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LanguageCode = "en",
                            LocationText = "Cairo, Egypt",
                            ProjectCardId = 1,
                            Title = "Residential Solar Install"
                        },
                        new
                        {
                            Id = 2,
                            LanguageCode = "ar",
                            LocationText = "القاهرة، مصر",
                            ProjectCardId = 1,
                            Title = "تركيب خلايا شمسية سكنية"
                        },
                        new
                        {
                            Id = 3,
                            LanguageCode = "en",
                            LocationText = "Alexandria, Egypt",
                            ProjectCardId = 2,
                            Title = "Commercial Solar Farm"
                        },
                        new
                        {
                            Id = 4,
                            LanguageCode = "ar",
                            LocationText = "الإسكندرية، مصر",
                            ProjectCardId = 2,
                            Title = "مزرعة طاقة شمسية تجارية"
                        });
                });

            modelBuilder.Entity("SolarSystem.Models1.Models.ProjectHomePageCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageRelativePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ProjectHomePageCards");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageRelativePath = "/images/projects/project1.jpg"
                        },
                        new
                        {
                            Id = 2,
                            ImageRelativePath = "/images/projects/project2.jpg"
                        });
                });

            modelBuilder.Entity("SolarSystem.Models1.Models.Section", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("Sections");

                    b.HasData(
                        new
                        {
                            Id = 1
                        },
                        new
                        {
                            Id = 2
                        });
                });

            modelBuilder.Entity("SolarSystem.Models1.Models.SectionTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SectionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SectionId");

                    b.ToTable("SectionTranslations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LanguageCode = "en",
                            Name = "Solar Panels",
                            SectionId = 1
                        },
                        new
                        {
                            Id = 2,
                            LanguageCode = "en",
                            Name = "Inverters",
                            SectionId = 2
                        },
                        new
                        {
                            Id = 3,
                            LanguageCode = "ar",
                            Name = "الألواح الشمسية",
                            SectionId = 1
                        },
                        new
                        {
                            Id = 4,
                            LanguageCode = "ar",
                            Name = "المحولات",
                            SectionId = 2
                        });
                });

            modelBuilder.Entity("SolarSystem.Models1.Models.CustomerFeedBack", b =>
                {
                    b.HasOne("SolarSystem.Models1.Models.Customer", "Customer")
                        .WithMany("CustomerFeedBacks")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("SolarSystem.Models1.Models.CustomerFeedbackTranslation", b =>
                {
                    b.HasOne("SolarSystem.Models1.Models.CustomerFeedBack", "CustomerFeedback")
                        .WithMany("Translations")
                        .HasForeignKey("CustomerFeedbackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CustomerFeedback");
                });

            modelBuilder.Entity("SolarSystem.Models1.Models.CustomerTranslation", b =>
                {
                    b.HasOne("SolarSystem.Models1.Models.Customer", "Customer")
                        .WithMany("Translations")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("SolarSystem.Models1.Models.Image", b =>
                {
                    b.HasOne("SolarSystem.Models1.Models.Product", "Product")
                        .WithMany("Images")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("SolarSystem.Models1.Models.Product", b =>
                {
                    b.HasOne("SolarSystem.Models1.Models.Section", "Section")
                        .WithMany("Products")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Section");
                });

            modelBuilder.Entity("SolarSystem.Models1.Models.ProductTranslation", b =>
                {
                    b.HasOne("SolarSystem.Models1.Models.Product", "Product")
                        .WithMany("Translations")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("SolarSystem.Models1.Models.ProjectCardTranslation", b =>
                {
                    b.HasOne("SolarSystem.Models1.Models.ProjectHomePageCard", "ProjectCard")
                        .WithMany("Translations")
                        .HasForeignKey("ProjectCardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProjectCard");
                });

            modelBuilder.Entity("SolarSystem.Models1.Models.SectionTranslation", b =>
                {
                    b.HasOne("SolarSystem.Models1.Models.Section", "Section")
                        .WithMany("Translations")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Section");
                });

            modelBuilder.Entity("SolarSystem.Models1.Models.Customer", b =>
                {
                    b.Navigation("CustomerFeedBacks");

                    b.Navigation("Translations");
                });

            modelBuilder.Entity("SolarSystem.Models1.Models.CustomerFeedBack", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("SolarSystem.Models1.Models.Product", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("Translations");
                });

            modelBuilder.Entity("SolarSystem.Models1.Models.ProjectHomePageCard", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("SolarSystem.Models1.Models.Section", b =>
                {
                    b.Navigation("Products");

                    b.Navigation("Translations");
                });
#pragma warning restore 612, 618
        }
    }
}
